# Generated by Django 3.0.2 on 2020-01-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creation_date', models.DateField()),
                ('external', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capital', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('internal', models.BooleanField(default=True)),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('state', models.CharField(choices=[('n', 'new'), ('i', 'in process'), ('p', 'pending'), ('c', 'closed'), ('r', 'rejected')], default='o', max_length=1, null=True)),
                ('creation_date', models.DateField()),
                ('content', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='in Minutes')),
                ('contributor', models.ManyToManyField(blank=True, to='myTickets.Person')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTickets.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myTickets.Country'),
        ),
    ]
