# Generated by Django 3.0.2 on 2020-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='duration',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contributor',
            field=models.ManyToManyField(blank=True, null=True, to='myTickets.Person'),
        ),
    ]
