# Generated by Django 3.0.2 on 2020-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTickets', '0004_auto_20200111_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('n', 'new'), ('i', 'in process'), ('p', 'pending'), ('c', 'closed'), ('r', 'rejected')], default='n', max_length=1, null=True),
        ),
    ]
