# Generated by Django 3.0.2 on 2020-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTickets', '0005_auto_20200111_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('n', 'new'), ('i', 'in process'), ('p', 'pending'), ('c', 'cancel'), ('d', 'done')], default='n', max_length=1, null=True),
        ),
    ]
