# Generated by Django 3.0.2 on 2020-01-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTickets', '0007_auto_20200112_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myTickets.Company'),
            preserve_default=False,
        ),
    ]
