# Generated by Django 3.0.2 on 2020-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTickets', '0008_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
